services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: Services/UserService/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/health_system.pfx
    volumes:
      - "$HOME/.aspnet/https:/https"
      - "$HOME/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys"
  postgres: 
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_booking_db
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=flywotbl@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=Wertyqin923134
    ports:
      - "5050:80"
    depends_on:
      - "postgres"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:
