# This is a generated file. Not intended for manual editing.
services:
  userservice:
    build:
      context: "/home/simofono/Development/C#/HealthcareBookingSystem"
      dockerfile: "Services/UserService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/UserService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "userservice:dev"
    ports: []
    volumes:
    - "/home/simofono/.nuget/packages:/root/.nuget/packages"
    - "/home/simofono/Development/C#/HealthcareBookingSystem/Services/UserService:/app:rw"
    - "/home/simofono/Development/C#/HealthcareBookingSystem:/src:rw"
    working_dir: "/app"
